parse_config:
  zmk_keycode_map:
    JIS_MINUS: "-"
    JIS_EQUAL: "="
    JIS_CARET: "^"
    JIS_TILDE: "~"
    JIS_AT: "@"
    JIS_GRAVE: "`"
    JIS_LBKT: "["
    JIS_LBRC: "{"
    JIS_RBKT: "]"
    JIS_RBRC: "}"
    JIS_SEMI: ";"
    JIS_PLUS: "+"
    JIS_COLON: ":"
    JIS_ASTERISK: "*"
    JIS_BACKSLASH: "\\"
    JIS_UNDERSCORE: "_"
    JIS_YEN: "¥"
    JIS_PIPE: "|"
    JIS_SLASH: "/"
    JIS_QUESTION: "?"
    JIS_EXCL: "!"
    JIS_DQT: '"'
    JIS_HASH: "#"
    JIS_DOLLAR: "$"
    JIS_PERCENT: "%"
    JIS_AMPERSAND: "&"
    JIS_SQT: "'"
    JIS_LPAR: "("
    JIS_RPAR: ")"
    JIS_LT: "<"
    JIS_GT: ">"
